### ISSUE TITLE
Loss of compatibility with some extensions

### ISSUE THREAD

**Issue by Filip013** [dsivasuthan/change-all-ui-fonts#3]
Hello! I use this extension mainly to study Chinese. I use it alongside the Zhongzhong extension to force both the webpage and the Zhongzhong pop-up window to display text in the same font (DFKai-SB).

But since the latest update, I can no longer force the same font in the Zhongzhong pop-up window. I am also unhappy with how your extension now integrates with iknow.jp (the site requires subscription). 

Right now, I'm dealing with the problem by deleting your extension and installing the previous version every time I want to use it. I hope this issue can be resolved.

**Comment by dsivasuthan** [comment]
I think the issue came about when I excluded "span" from taking the new font change. This was introduced to prevent Google sites (keep, calendar) from showing squares instead of icons. 

I will add an option to revert this change. Please keep using the old version for now. I will comment again once I push a change and Google reviews it. 

Thanks for taking the time to create the ticket.

**Comment by dsivasuthan** [comment]
Never got the time to implement the change. There is a better extention called Dark Reader.
